import type { Metadata } from "next";
import { Zen_Maru_Gothic, Kosugi_Maru } from "next/font/google";
import "./globals.css";

const zenMaruGothic = Zen_Maru_Gothic({
  variable: "--font-zen-maru-gothic",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const kosugiMaru = Kosugi_Maru({
  variable: "--font-kosugi-maru",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "kids-planner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${zenMaruGothic.variable} ${kosugiMaru.variable} antialiased bg-ivory text-black`}
      >
        {children}
      </body>
    </html>
  );
}
